FROM hortonworks/ambari-base

RUN yum install wget curl ntp -y && yum clean all

RUN yum history new{{#arguments.updateLibraries}} && yum update -y{{/arguments.updateLibraries}} && yum clean all

RUN wget -nv {{arguments.ambariRepoFileUrl}} -O /etc/yum.repos.d/ambari.repo

RUN yum install ambari-server ambari-agent{{#arguments.kerberosEnabled}} krb5-libs krb5-server krb5-workstation{{/arguments.kerberosEnabled}} -y && yum clean all

RUN sed -i "s/^hostname=localhost/hostname={{arguments.fqdn}}/g" /etc/ambari-agent/conf/ambari-agent.ini

{{#arguments.kerberosEnabled}}
ADD krb5.conf /etc/krb5.conf
ADD kdc.conf /var/kerberos/krb5kdc/kdc.conf
ADD kadm5.acl /var/kerberos/krb5kdc/kadm5.acl

RUN /usr/sbin/kdb5_util create -s -P password
RUN /usr/sbin/kadmin.local -q 'addprinc -pw admin admin/admin' -w password
RUN krb5kdc start
#RUN kadmin start
{{/arguments.kerberosEnabled}}


RUN ambari-server setup -j /usr/jdk64/jdk1.7.0_67

RUN ambari-server start && ambari-agent start