#!/bin/sh

# vagrant-checkstatus.sh generated by https://github.com/timveil/hdp-vagrant-generator on 2/16/16 9:11 AM



echo " "
echo "---------------------------------------------------------------------------------------------------------------"
echo "----- Waiting for Cluster Install to Finish"
echo "---------------------------------------------------------------------------------------------------------------"
echo " "

PROGRESS=0
until [ $PROGRESS -eq 100 ]; do
    PROGRESS=`curl --silent --show-error -H "X-Requested-By: ambari" -X GET -u admin:admin http://spark.hdp.local:8080/api/v1/clusters/spark/requests/1 2>&1 | grep -oP '\"progress_percent\"\s+\:\s+\K[0-9]+'`
    echo -ne "$PROGRESS percent complete!"\\r
    sleep 5
done