#!/bin/sh

# vagrant-checkstatus.sh generated by https://github.com/timveil/hdp-vagrant-veil.hdp.generator on 6/9/16 2:59 PM



echo " "
echo "---------------------------------------------------------------------------------------------------------------"
echo "----- Waiting for Cluster Install to Finish"
echo "---------------------------------------------------------------------------------------------------------------"
echo " "

PROGRESS=0
until [ $PROGRESS -eq 100 ]; do
    PROGRESS=`curl --silent --show-error -H "X-Requested-By: ambari" -X GET -u admin:admin http://hdp-common-secure.hdp.local:8080/api/v1/clusters/hdp-common-secure/requests/1 2>&1 | grep -oP '\"progress_percent\"\s+\:\s+\K[0-9]+'`
    echo -ne "$PROGRESS percent complete!"\\r
    sleep 5
done